In [1]:
!pip install --upgrade tensorflow

In [2]:
from typing import List, Dict, Mapping, Tuple

import jax
import jax.numpy as jnp
import jax.random as jrand
import flax
import flax.linen as nn
from flax.training import train_state  # Useful dataclass to keep train state
import optax
import tensorflow as tf
import pdb
import functools

def println(*args):
  for arg in args:
    print(arg)


In [3]:
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
jax.devices()

[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0),
 TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1),
 TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0),
 TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1),
 TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0),
 TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1),
 TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0),
 TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]

In [4]:
DEVICE_COUNT = len(jax.devices())
DEVICE_COUNT

8

In [5]:
import dataclasses

@dataclasses.dataclass
class Config:
    vocab_size: int = 66
    batch_size: int = 8 # 512
    block_size: int = 8 # 64
    n_embed: int = 8 # 256
    num_heads: int = 8
    num_layers: int = 6

config = Config()

# Dataset

In [6]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-05-02 04:01:13--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.3’

input.txt.3         100%[===================>]   1.06M  --.-KB/s    in 0.05s   

2024-05-02 04:01:14 (20.2 MB/s) - ‘input.txt.3’ saved [1115394/1115394]



In [7]:
from dataclasses import dataclass
from typing import Dict, List, Mapping, Tuple

import jax
import jax.numpy as jnp
import tensorflow as tf
import requests

# Below would result in a minibatch size of 32.
BATCH_SIZE = config.batch_size # how many independent sequences will we process in parallel?
BLOCK_SIZE = config.block_size # what is the maximum context length for predictions?

with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# Create chars vocubulary using all the unique characters in the text.
chars = sorted(list(set(text)))
VOCAB_SIZE = len(chars)

# Create mapping from characters to integers.
stoi = {ch: i for i, ch in enumerate(chars)}

# Create reverse mapping from integers to characters.
itos = {i: ch for i, ch in enumerate(chars)}

# Create encode, decode function.
def encode(s: str, stoi: Mapping[str, int]) -> List[int]:
  return [stoi[c] for c in s]

def decode(tokens: List[int], itos: Mapping[int, str]) -> str:
  return ''.join([itos[i] for i in tokens])

println(encode("hii there", stoi), decode(encode("hii there", stoi), itos))

# Let's now split up the data into train and validation sets.
data = jnp.array(encode(text, stoi), dtype=jnp.int64)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


<ipython-input-7-fc26583afcbd>:36: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in array is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  data = jnp.array(encode(text, stoi), dtype=jnp.int64)


In [8]:
def create_dataset(training: bool = True):
  global train_data, val_data
  data = train_data if training else val_data
  dataset = (tf.data.Dataset.from_tensor_slices(data)
                .repeat()
                .batch(BLOCK_SIZE+1)
                .map(lambda input: (input[:BLOCK_SIZE], input[1:BLOCK_SIZE+1]),
                     num_parallel_calls=tf.data.AUTOTUNE)
                .batch(BATCH_SIZE)
                .as_numpy_iterator())
  return dataset

def get_batch(dataset):
  batch = next(dataset)
  return jnp.array(batch)

In [9]:
train_dataset = create_dataset(training=True)
val_dataset = create_dataset(training=False)

### test dataset

In [10]:
xb, yb = get_batch(train_dataset)
println("inputs", xb, "inputs shape", xb.shape)
println("targets", yb, "targets shape", yb.shape)
# for b in range(BATCH_SIZE): # batch dimension
#     for t in range(BLOCK_SIZE): # time dimension
#         context = xb[b, :t+1]
#         target = yb[b,t]
#         print(f"when input is {context.tolist()} the target: {target}")

inputs
[[18 47 56 57 58  1 15 47]
 [47 64 43 52 10  0 14 43]
 [53 56 43  1 61 43  1 54]
 [53 41 43 43 42  1 39 52]
 [ 1 44 59 56 58 46 43 56]
 [ 1 46 43 39 56  1 51 43]
 [57 54 43 39 49  8  0  0]
 [50 50 10  0 31 54 43 39]]
inputs shape
(8, 8)
targets
[[47 56 57 58  1 15 47 58]
 [64 43 52 10  0 14 43 44]
 [56 43  1 61 43  1 54 56]
 [41 43 43 42  1 39 52 63]
 [44 59 56 58 46 43 56  6]
 [46 43 39 56  1 51 43  1]
 [54 43 39 49  8  0  0 13]
 [50 10  0 31 54 43 39 49]]
targets shape
(8, 8)


# Model

In [11]:
from typing import List, Dict, Mapping, Tuple

import jax
import jax.numpy as jnp
import jax.random as jrand
import flax.linen as nn
from flax.training import train_state  # Useful dataclass to keep train state
import optax
import tensorflow as tf
import pdb
import functools

class SingleHeadAttention(nn.Module):
  """Implements a simple SingleHeadAttention layer for a single example from batch."""

  head_size: int
  num_tokens: int
  dropout_rate: float = 0.2
  use_causal_mask: bool = True  # if True, only attend to past tokens.

  @nn.compact
  def __call__(self, tokens: jnp.array, training: bool):
    """Tokens, each with some channel dim."""
    # Use separate single dense layers for calculating keys, query, values
    keys = nn.Dense(self.head_size, use_bias=False)(tokens)
    queries = nn.Dense(self.head_size, use_bias=False)(tokens)
    values = nn.Dense(self.head_size, use_bias=False)(tokens)

    mask = (
        jnp.tril(jnp.ones(shape=(self.num_tokens, self.num_tokens)))
        if self.use_causal_mask
        else jnp.ones(shape=(self.num_tokens, self.num_tokens))
    )

    # compute attention score.
    # import pdb; pdb.set_trace()
    wei = jnp.dot(queries, keys.T) / jnp.sqrt(self.head_size)
    wei = jnp.where(mask == 0, -jnp.inf, wei)
    wei = nn.softmax(wei, axis=-1)

    attention_values = jnp.dot(
        wei, values
    )  # (num_tokens, num_tokens) * (num_tokens, head_size)
    attention_values = nn.Dropout(rate=self.dropout_rate, deterministic=True)(
        attention_values
    )
    return attention_values  # (num_tokens, head_size)


class MultiHeadAttention(nn.Module):
  """Implements a MultiHeadAttention layer for a single example from batch."""

  head_size: int
  num_heads: int
  num_tokens: int
  dropout_rate: float = 0.2

  def setup(self):
    self.heads = [
        SingleHeadAttention(
            head_size=self.head_size, num_tokens=self.num_tokens
        )
        for _ in range(self.num_heads)
    ]

    # Project concatenated output from all attention heads to final output
    # dimension, which is head_size * num_heads.
    self.projection = nn.Dense(features=self.num_heads * self.head_size)
    self.dropout = nn.Dropout(rate=self.dropout_rate, deterministic=True)

  def __call__(self, tokens: jnp.array, training: bool):
    output_from_each_head = []
    for h in self.heads:
      head_output = h(tokens, training)
      output_from_each_head.append(head_output)

    # Run multiple attention heads in parallel and concatenate
    # their output along channel dimension, i.e., dim==-1
    out_from_all_heads = jnp.concatenate(output_from_each_head, axis=-1)

    projection = self.projection(out_from_all_heads)
    return self.dropout(projection)

class FeedForward(nn.Module):
  output_size: int

  def setup(self):
    # Attention paper uses 4 times token_info_size when doing linear transformation
    # and then projects it back to token_info_size in linear transformation layer.
    self.ffwd = nn.Dense(features=4 * self.output_size)
    self.projection = nn.Dense(self.output_size)

  def __call__(self, x, training: bool):
    x = nn.relu(self.ffwd(x))
    x = self.projection(x)
    return x

class TransformerEncoderBlock(nn.Module):
  num_heads: int
  # output_size = head_size * num_heads, is the final embedding dimension you get after concatenating from all heads.
  output_size: int
  num_tokens: int

  def setup(self):
    # communication.
    # each single head will produce head_size worth of info for key, value, querie. You concatenate all of them to get the final output_size.
    self.head_size = self.output_size // self.num_heads
    self.self_attention_heads = MultiHeadAttention(num_heads=self.num_heads,
                                                   head_size = self.head_size,
                                                   num_tokens=self.num_tokens)

    # computation.
    self.computation_layer = FeedForward(output_size=self.output_size)

    self.ln1 = nn.LayerNorm()
    self.ln2 = nn.LayerNorm()

    self.dropout = nn.Dropout(rate=0.2, deterministic=True)

  def __call__(self, x, training: bool):
    # transformer encoder forward pass
    x = x + self.self_attention_heads(self.ln1(x), training)

    x = x + self.computation_layer(self.ln2(x), training)

    x = self.dropout(x)
    return x

class LanguageModel(nn.Module):
  """Reads one char and predicits the next char."""
  vocab_size: int # number of vocabulary (number of rows of embedding table)
  n_embed: int # embedding dim after lookup
  num_tokens: int # block size, i.e., number of tokens attention block is looking at once
  num_heads: int
  num_layers: int

  def setup(self):
    # number of channels you want to use for store info for each token.
    self.C = self.vocab_size

    self.token_embedding_table = nn.Embed(num_embeddings=self.vocab_size, features=self.n_embed)

    self.pos_embedding_table = nn.Embed(num_embeddings=self.num_tokens, features=self.n_embed)

    # Since, there are 4 heads, each head only needs to output token_info of size 8.
    # Concantenate token_info from all 4 heards, gives us 32
    self.blocks = [
        TransformerEncoderBlock(num_heads=self.num_heads,
                                output_size=self.n_embed,
                                num_tokens=self.num_tokens) for _ in range(self.num_layers)
    ]
    self.ln = nn.LayerNorm()
    self.lang_model_head = nn.Dense(features=self.C)

  def __call__(self, block_of_tokens: jnp.array, training: bool):
    """Accepts a block of tokens, like [0, 1, 2, 3, 4, 5, 6, 7]."""
    # generate emb for each token. output: (num_tokens, n_embed)
    token_embs = self.token_embedding_table(block_of_tokens)

    # generate position embs for each token.
    num_pos = block_of_tokens.shape[0]
    positions = jnp.arange(0, num_pos)
    pos_embs = self.pos_embedding_table(positions)

    # generate actual input to attention, x, which is sum of token_embs + pos_embs
    x = token_embs + pos_embs

    # feed x into self-attention head.
    # language model, forward pass, block_of_tokens
    for i in range(self.num_layers):
      x = self.blocks[i](x, training)

    x = self.ln(x)

    # generate logits for each token. output: (T, channels for info -- C)
    token_logits = self.lang_model_head(x)

    return token_logits


class LanguageModelBatch(nn.Module):
  """Extends MultiHeadAttention to work on a batch of data."""
  vocab_size: int # number of vocabulary (number of rows of embedding table)
  n_embed: int # embedding dim after lookup
  num_tokens: int # block size, i.e., number of tokens attention block is looking at once
  num_heads: int
  num_layers: int

  @nn.compact
  def __call__(self, tokens: jnp.array, training: bool):
    return jax.vmap(LanguageModel(
        vocab_size=self.vocab_size,
        n_embed=self.n_embed,
        num_tokens=self.num_tokens,
        num_heads=self.num_heads,
        num_layers=self.num_layers),
                    in_axes=(0, None),  # tokens, training
                    out_axes=(0),)(tokens, training)

In [12]:
def forward_pass(params, state, batch, training, rng):
  inputs, targets = batch
  logits = state.apply_fn({"params": params}, inputs, training, rngs={"dropout": rng})
  loss = optax.softmax_cross_entropy_with_integer_labels(logits, targets)
  loss = loss.mean()
  return loss

In [13]:
def backward_pass(state, batch, training, rng):
  grad_fn = jax.value_and_grad(forward_pass, argnums=(0))
  loss, grads = grad_fn(state.params, state, batch, training, rng)

  state = state.apply_gradients(grads=grads)
  return state, loss

In [14]:
def backward_pass_pmap(state, batch, training, rng):
  grad_fn = jax.value_and_grad(forward_pass, argnums=(0))
  loss, grads = grad_fn(state.params, state, batch, training, rng)

  loss = jax.lax.pmean(loss, axis_name="devices")
  grads = jax.lax.pmean(grads, axis_name="devices")

  state = state.apply_gradients(grads=grads)
  return state, loss

In [15]:
def train_step(state, batch, training, rng):
  state, loss = backward_pass(state, batch, training, rng)
  return state, loss

train_step_pmap = jax.pmap(
    jax.jit(train_step), in_axes=(0, 0, None, 0), out_axes=(0), axis_name="devices")

In [16]:
def get_batch_pmap(dataset):
  inputs, targets = get_batch(dataset)
  inputs = inputs.reshape((jax.device_count(), -1, inputs.shape[-1]))
  targets = targets.reshape((jax.device_count(), -1, targets.shape[-1]))
  return inputs, targets


In [17]:
model = LanguageModelBatch(vocab_size=config.vocab_size,
                      n_embed=config.n_embed,
                      num_tokens=config.block_size,
                      num_heads=config.num_heads,
                      num_layers=config.num_layers)

In [18]:
inputs, targets = get_batch(train_dataset)
inputs.shape, targets.shape

((8, 8), (8, 8))

In [19]:
inputsp, targetsp = get_batch_pmap(train_dataset)
inputsp.shape, targetsp.shape

((8, 1, 8), (8, 1, 8))

In [20]:
output, params = model.init_with_output(jax.random.PRNGKey(99), inputs, training=False)
params = params["params"]

output.shape

(8, 8, 66)

In [21]:
opt = optax.adam(learning_rate=0.0001)
state = train_state.TrainState.create(apply_fn=model.apply, params=params, tx=opt)

In [22]:
states = jax.device_put_replicated(state, jax.local_devices())

In [23]:
backward_pass(state, get_batch(train_dataset), False, jax.random.PRNGKey(99))

(TrainState(step=1, apply_fn=<bound method Module.apply of LanguageModelBatch(
     # attributes
     vocab_size = 66
     n_embed = 8
     num_tokens = 8
     num_heads = 8
     num_layers = 6
 )>, params={'LanguageModel_0': {'blocks_0': {'computation_layer': {'ffwd': {'bias': Array([ 9.9999292e-05, -9.9999255e-05,  9.9999248e-05, -9.9999321e-05,
        -9.9999292e-05, -9.9999146e-05, -9.9999255e-05,  9.9999321e-05,
        -9.9999197e-05,  9.9999263e-05, -9.9998331e-05, -9.9999161e-05,
        -9.9999292e-05, -9.9999292e-05,  9.9999212e-05,  9.9999241e-05,
        -9.9999292e-05, -9.9999190e-05, -9.9998957e-05,  9.9999233e-05,
        -9.9999263e-05, -9.9999277e-05, -9.9999241e-05,  9.9999233e-05,
         9.9999292e-05,  9.9988014e-05, -9.9999241e-05,  9.9999292e-05,
        -9.9999197e-05,  9.9999306e-05, -9.9997866e-05, -9.9999299e-05],      dtype=float32), 'kernel': Array([[ 0.08368423, -0.42215985, -0.07026786,  0.14903775,  0.41839692,
          0.27839348,  0.23901537, -0.093

In [24]:
states, loss = train_step_pmap(states, get_batch_pmap(train_dataset), False, jax.random.split(jax.random.PRNGKey(9),
                                                                                              num=DEVICE_COUNT))

In [25]:
rngs = jax.random.split(jax.random.PRNGKey(9), num=DEVICE_COUNT)
for step in range(1):
  rngs = jax.random.split(rngs[0], num=DEVICE_COUNT)
  train_batch = get_batch_pmap(train_dataset)
  states, loss = train_step_pmap(states, train_batch, False, rngs)

  print("loss", loss[0], "step", step) if step%100==0 else None

loss 4.6886034 step 0


# Generating

In [26]:
T = config.block_size

state = jax.tree_map(lambda x: x[0], states)

state_apply_jit = jax.jit(state.apply_fn)

context = jnp.tile(jnp.array([52], dtype=jnp.int32), T)
context = context[None, -T:]
key = jrand.PRNGKey(99)

for _ in range(100):
  next_token_logits = state_apply_jit({"params": state.params}, context[:, -T:], False)

  key, split_key = jrand.split(key)
  new_token = jax.random.categorical(key, next_token_logits[:, -1, :], axis=-1, shape=(1, 1))

  context = jnp.concatenate([context, new_token], axis=1)


print(decode(context.tolist()[0], itos))


<ipython-input-26-f1f558d2c63c>:3: DeprecationWarning: jax.tree_map is deprecated: use jax.tree.map (jax v0.4.25 or newer) or jax.tree_util.tree_map (any JAX version).
  state = jax.tree_map(lambda x: x[0], states)


nnnnnnnnq&qSs3uqzrk..O3PCG,3KXao'TFxlzN?,M?.urk$u lGJ?skk3N3,!,BGJi3.O3JzL:Y?oRpuznJMx':srG LQof3z&YoK,UuX'Y
